name: release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Determine next version
        id: git-cliff
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        with:
          config: cliff.toml
          args: --bump --unreleased
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: steps.git-cliff.outputs.version != ''
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          tag_name: ${{ steps.git-cliff.outputs.version }}
          body: ${{ steps.git-cliff.outputs.content }}
          make_latest: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
